apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx-chart.fullname" . }}
  labels:
    {{- include "nginx-chart.labels" . | nindent 4 }} 
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nginx-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nginx-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }} 
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}" 
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
          ports:
            - name: http 
              containerPort: 80 
              protocol: TCP 
          livenessProbe: 
            httpGet: 
              path: /health 
            initialDelaySeconds: 15  
            timeoutSeconds: 5 
            periodSeconds: 10 
          readinessProbe: 
            httpGet:  http
              path: /health  
              port: http  
            initialDelaySeconds: 5  
            timeoutSeconds: 3 
            periodSeconds: 5 
          env: 
          - name: message 
            valueFrom: 
              configMapKeyRef:
                name: {{ include "nginx-chart.fullname" . }}-configmap 
                key: message 
          volumeMounts:  томов
          - name: nginx-conf 
            mountPath: /etc/nginx/conf.d/default.conf 
            subPath: default.conf 
      volumes: # тома name: nginx-conf 
        configMap:  configmap
          name: {{ include "nginx-chart.fullname" . }}-configmap 
          items: 
          - key: nginx-сonf 
            path: default.conf 